title: marcelofpfelix title
name: marcelofpfelix - webpage
description: > # this means to ignore newlines
  This is a  description for your new site here.
  It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

author: authorname
email: marcelo.felix@maro.live
twitter_username: marcelofpfelix
github_username:  marcelofpfelix
repository: marcelofpfelix/marcelofpfelix.github.io

#Global Configuration
timezone: Europe/Lisbon
theme: minima
markdown: kramdown
